name: Remove awaiting-response label on user comment

on:
  issue_comment:
    types: [created]

jobs:
  remove-label:
    runs-on: ubuntu-latest
    if: github.event.sender.login != github.repository_owner
    permissions:
      issues: write
    steps:
      - name: Remove label
        uses: actions/github-script@v8
        with:
          script: |
            const labels = github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            if (labels.some(label => label.name === "awaiting-response")) {
              github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: 'awaiting-response'
              })
            }
