name: Mark and close stale issues

on:
  schedule:
    - cron: "18 8 * * SAT"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v10
        with:
          only-labels: awaiting-response
          stale-issue-label: stale
          days-before-stale: 40
          days-before-close: 7
          stale-issue-message: >
            This issue has been marked as stale because it has been open for more than 30 days without response.
            If you can provide more information, please do so â€” otherwise, this issue will be closed in 7 days.
          close-issue-message: >
            If this is still an issue, feel free to add comments or create a new one with updated info.
